apiVersion: config.openshift.io/v1
kind: DataProcessingUnitConfig
metadata:
  labels:
    app.kubernetes.io/name: dpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataprocessingunitconfig-sample
spec:
  # Apply this config to all DPUs with label dpu=enabled
  dpuSelector:
    matchLabels:
      dpu: "enabled"
  # Desired VF count for matched DPUs
  vfCount: 8
