{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "dpu-operator.fullname" . }}-validating-webhook
  labels:
    {{- include "dpu-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "dpu-operator.fullname" . }}-serving-cert
  {{- end }}
webhooks:
  - name: vdpuoperatorconfig.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "dpu-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-config-openshift-io-v1-dpuoperatorconfig
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    rules:
      - apiGroups:
          - config.openshift.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - dpuoperatorconfigs
    sideEffects: None
{{- end }}
