{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "dpu-operator.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dpu-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dpu-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dpu-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "dpu-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "dpu-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "dpu-operator.fullname" . }}-selfsigned
  secretName: {{ include "dpu-operator.fullname" . }}-webhook-server-cert
{{- end }}
