{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dpu-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dpu-operator.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "dpu-operator.fullname" . }}-webhook-server-cert
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "dpu-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
